version: "3.8"
services:
  rstudio:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - type: bind
        source: ./
        target: /home/rstudio/
      - logvolume01:/var/log
    links:
      - postgis
    environment:
      - DISABLE_AUTH=true
  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=WRRI
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      # - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./wrri_pg_bak:/etc/postgresql/wrri_pg_bak
      - ./schema.sh:/docker-entrypoint-initdb.d/schema.sh
      # - ./loadtigerdata.sh:/tmp/loadtigerdata.sh
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - "5430:5432"
volumes:
  logvolume01: {}