---
title: "HUC12_BMP_Feature_Creation"
author: "Corey White"
date: "11/18/2020"
output:
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Nutrient Loading Model

```{r libs, include=FALSE}
library(reshape2) # (tidy) R provides a variety of methods for reshaping data prior to analysis.
library(dplyr) # (tidy) dplyr is a grammar of data manipulation, providing a consistent set of verbs that help you solve the most common data manipulation challenges:
library(tidyr)
# library(lme4) # lme4 provides functions for fitting and analyzing mixed models: linear (lmer), generalized linear(glmer) and nonlinear (nlmer.)
library(ggplot2) # (tidy) gplot2 is a system for declaratively creating graphics
# library(xlsx) # Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file formats.
# library(rstan) # Stan is a state-of-the-art platform for statistical modeling and high-performance statistical computation. 
library(rstudioapi) # Access the RStudio API (if available) and provide informative error messages when it's not.
# library(loo)  # Efficient Leave-One-Out Cross-Validation and WAIC for Bayesian Models
library(MASS) # Support Functions and Datasets for Venables and Ripley's MASS
# library(rcompanion) # Functions to Support Extension Education Program Evaluation
library(ggpubr) # 'ggplot2' Based Publication Ready Plots
# library(matrixStats) # Functions that Apply to Rows and Columns of Matrices (and to Vectors)
library(pacman) # Package Management Tool
library(cowplot) # add-on to ggplot. It provides various features that help with creating publication-quality figures, such as a set of themes, functions to align plots and arrange them into complex compound figures, and functions that make it easy to annotate plots and or mix plots with images.
library(hexbin) # Bivariate Binning Into Hexagon Cells
library(RColorBrewer)
library(rgeos)
library(sf)
require(gridExtra)

```


### Connect to database
```{r connect, message=F, warning=F}
library(RPostgreSQL)
library(postGIStools)
library(RColorBrewer)

con <- dbConnect(PostgreSQL(), dbname = "WRRI", user = "postgres",
                 host = "postgis",
                 port="5432")
```

## HUC12 Subwatersheds

Get HUC12 in study area
```{r huc12studyarea}

hu12_df <- get_postgis_query(con, 
    "SELECT *
     FROM subwatersheds",
geom_name = "geom")
```

Get Study area
```{r study_area}
aoi_df <- get_postgis_query(con, 
    "SELECT ST_UNION(fl.geom,jl.geom) as geom 
		FROM jordan_lake_watershed as jl, falls_lake_watershed as fl",
geom_name = "geom")
```

Get Counties
```{r counties}
counties_df <- get_postgis_query(con, 
    "SELECT countyname, geom 
		FROM counties",
geom_name = "geom")
```


```{r studyarea}
plot(counties_df,  border=c('black'))
plot(hu12_df, border="grey", add=T)
plot(aoi_df,  border=c('blue'), add=T)
```


## BMPS & SCM
### City of Greensboro
Calculating the total area of BMP & SCM features by type
```{r}
greensboro_bmp_area_df <- get_postgis_query(con,
"SELECT featuretyp, bmptype, (SUM(ST_AREA(geom)) / 1e6) as area
FROM sw_waterbodies_bmp_scm_greensboro
GROUP BY featuretyp, bmptype")

ggplot(greensboro_bmp_area_df, aes(y=bmptype, x=featuretyp, fill= area)) + 
  geom_tile() +
  scale_fill_distiller(palette = "YlGnBu", trans='log2', direction=1) +
  labs(
       title = "BMP & SCM Type Area (km^2)",
       subtitle = "City of Greensboro",
       x = "BMP/SCM Type",
       y = "Feature Type") +
  geom_text(aes(label=sprintf("%0.4f", area)),color="white", face="bold", size=rel(3.5)) 

```

Calculating the total number of BMP & SCM features by type
```{r}
greensboro_bmp_count_df <- get_postgis_query(con,
"SELECT featuretyp, bmptype, COUNT(*) as count
FROM sw_waterbodies_bmp_scm_greensboro
GROUP BY featuretyp, bmptype")

ggplot(greensboro_bmp_count_df, aes(y=bmptype, x=featuretyp, fill= count)) + 
  geom_tile() +
  scale_fill_distiller(palette = "YlGnBu", trans='log2', direction=1) +
  labs(color="Buiding Inclusion",
       title = "BMP & SCM Type Count",
       subtitle = "City of Greensboro",
       x = "BMP/SCM Type",
       y = "Feature Type") +
  geom_text(aes(label= count),color="white", face="bold", size=rel(3.5))
```



```{r}
query = paste("SELECT bmp.featuretyp, bmp.bmptype, (SUM(ST_AREA(bmp.geom)) / 1e6) as area, sa.geom
FROM sw_waterbodies_bmp_scm_greensboro as bmp
JOIN huc12_study_area as sa ON ST_CONTAINS(sa.geom, ST_CENTROID(bmp.geom))
GROUP BY featuretyp, bmptype, sa.geom")

greensboro_bmp_area_gdf <- st_read(con,query = query)

```

Plot the data
```{r}
greensboro_bmp_area_gdf %>%
ggplot() +
    facet_grid(.~featuretyp) +
    geom_sf(aes(fill = area)) +
    scale_fill_viridis_c(option = "YlGnBu",trans='log2')
```

```{r}
greensboro_bmp_area_gdf %>%
  filter(bmptype == 'Dry Waterbody' | bmptype =='Wet Waterbody')  %>%
ggplot() +
    facet_grid(featuretyp~bmptype) +
    geom_sf(aes(fill = area)) +
    scale_fill_viridis_c(trans='log2')
```


```{r}
query = paste('SELECT  
	bmp.assetid,
	bmp.featuretyp,
	bmp.bmptype,
	bmp.installdat,
	bmp.ownership,
	bmp.lifecycle,
	bmp.comments,
	sa.hu_12_name,
	(SUM(ST_AREA(bmp.geom)) / 1e6) as area,
	cast(avg(cast(bf.year_built as integer)) as integer) as mean_year,
	PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY cast(bf.year_built as integer)) as median_year,
	sa.geom
FROM sw_waterbodies_bmp_scm_greensboro as bmp
JOIN building_footprints as bf on ST_INTERSECTS(ST_Buffer(bmp.geom, 500), bf.geom)
JOIN huc12_study_area as sa on ST_INTERSECTS(bmp.geom, sa.geom)
GROUP BY 
		bmp.assetid,
		bmp.featuretyp,
		bmp.bmptype,
		bmp.installdat,
		bmp.ownership,
		bmp.lifecycle,
		bmp.comments,
		sa.hu_12_name,
		sa.geom
ORDER BY median_year'
)

greensboro_bmp_year_area_gdf <- st_read(con,query = query)

```



```{r}
head(greensboro_bmp_year_area_gdf, 5)
ggplot(greensboro_bmp_year_area_gdf, aes(x=median_year,y=area, group= bmptype)) + 
  geom_line() +
  #scale_fill_distiller(palette = "YlGnBu", direction=1) +
  labs(color="Buiding Inclusion",
       title = "BMP & SCM Type Count by Year",
       subtitle = "City of Greensboro",
       x = "BMP/SCM Type",
       y = "Feature Type") #+
  #geom_text(aes(label= area),color="white", face="bold", size=rel(3.5))
```

```{r Total-BMP/SCM-Area-(SqKm)-per-HUC12, fig.width=12, fig.height= 9, fig.align='center'}

counties_sf <- st_read(con, query= paste(
    "SELECT sa.geom 
		FROM counties, huc12_study_area as sa WHERE countyname = 'Guilford' and ST_INTERSECTS(counties.geom, sa.geom)"))

greensboro_bmp_year_area_gdf %>%
ggplot() +
   # facet_grid(year_built~.,rows = vars(5)) +
    geom_sf(data=counties_sf) +
    facet_wrap(median_year~., ncol = 10) +
    geom_sf(aes(fill = area)) +
    scale_fill_viridis_c(name="Total BMP/SCM Area (Sq Km)",trans='log2') + 
    theme_map() +
    labs( title = "Total BMP/SCM Area (Sq Km) per HUC12",
       subtitle = "1970 - 2014")

```

```{r bmp_count_per_subwatershed_facet_plot, fig.width=12, fig.height= 9, fig.align='center'}

#head(greensboro_bmp_year_area_gdf)
greensboro_bmp_year_area_gdf %>%
  filter(median_year >= 1950) %>%
  group_by(hu_12_name) %>% mutate(count=row_number(), cumarea=cumsum(area)) %>%
  ggplot(aes(x=median_year,y=count)) + 
  facet_wrap(hu_12_name~.) +
  geom_line(aes(x=median_year,y=count)) + 
  geom_point(aes(x=median_year,y=count)) + 
  scale_fill_continuous(type = "viridis") +
  theme_bw() +
  scale_y_continuous(trans='log10') +
  #scale_fill_distiller(palette = "YlGnBu", direction=1) +
  labs(
       title = "BMP & SCM Cumulative Count Per Subwatershed",
       subtitle = "",
       x = "BMP/SCM install Date Estimate (Median Age of Surrounding Development)",
       y = "Cumulative Total of BMP/SCM"
      )


```

```{r bmp_count_per_subwatershed_area_type_facet_plot, fig.width=12, fig.height= 9, fig.align='center'}

#head(greensboro_bmp_year_area_gdf)
greensboro_bmp_year_area_gdf %>%
  filter(median_year >= 1950) %>%
  group_by(hu_12_name) %>% mutate(count=row_number(), cumarea=cumsum(area)) %>%
  ggplot(aes(x=median_year,y=count)) + 
  facet_wrap(hu_12_name~ownership) +
  geom_line(aes(x=median_year,y=count, group=bmptype, color=bmptype)) + 
  geom_point(aes(x=median_year,y=count, group=bmptype, color=bmptype, cex=area)) + 
  scale_fill_continuous(type = "viridis") +
  theme_bw() +
  scale_y_continuous(trans='log10') +
  #scale_fill_distiller(palette = "YlGnBu", direction=1) +
  labs(
       title = "BMP & SCM Cumulative Count Per Subwatershed",
       subtitle = "by BMP/SCM Ownership and BMP/SCM Type",
       x = "BMP/SCM install Date Estimate (Median Age of Surrounding Development)",
       y = "Cumulative Total of BMP/SCM"
      )



```

```{r}
greensboro_bmp_year_area_gdf %>%
  filter(median_year >= 1950) %>%
  group_by(hu_12_name) %>% mutate(count=row_number(), cumarea=cumsum(area)) %>%
  ggplot(aes(x=median_year,y=count)) + 
  facet_wrap(hu_12_name~.) +
  geom_line(aes(x=median_year,y=count, group=bmptype, color=bmptype)) + 
  geom_point(aes(x=median_year,y=count, group=bmptype, color=bmptype, cex=cumarea)) + 
  scale_fill_continuous(type = "viridis") +
  theme_bw() +
  scale_y_continuous(trans='log2') +
  #scale_fill_distiller(palette = "YlGnBu", direction=1) +
  labs(
       title = "BMP & SCM Type Cumulative Count",
       subtitle = "",
       x = "BMP/SCM install Date Estimate (Median Age of Surrounding Development)",
       y = "Cumulative Total of BMP/SCM in HUC12"
      )
```

```{r bmp_count_per_subwatershed_area_facet_plot, fig.width=12, fig.height= 9, fig.align='center'}
greensboro_bmp_year_area_gdf %>%
  filter(median_year >= 1950) %>%
  group_by(hu_12_name) %>% mutate(cumarea=cumsum(area)) %>%
  ggplot(aes(x=median_year)) + 
  facet_wrap(hu_12_name~.) +
  geom_line(aes(x=median_year,y=cumarea, group=ownership, color=ownership)) + 
  geom_point(aes(x=median_year,y=cumarea, group=ownership, color=ownership)) + 
  scale_fill_continuous(type = "viridis") +
  theme_bw() +
  #scale_y_continuous(trans='log2') +
  #scale_fill_distiller(palette = "YlGnBu", direction=1) +
  labs(
       title = "BMP & SCM Cumulative Area KM2",
       subtitle = "by Ownership",
       x = "Median Age of Surrounding Development",
       y = "Cumulative Total Area of BMP/SCMs"
      )
```

```{r}
greensboro_bmp_year_area_gdf %>%
  filter(median_year >= 1960) %>%
  group_by(hu_12_name) %>% mutate(count=row_number(), cumarea=cumsum(area)) %>%
  ggplot(aes(x=median_year)) + 
  facet_wrap(hu_12_name~.) +
  geom_area(aes(x=median_year,y=count, fill=bmptype)) + 
  #geom_point(aes(x=median_year,y=count, group=bmptype, color=bmptype, cex=cumarea)) + 
  #scale_fill_continuous(type = "viridis") +
  theme_bw() +
  #scale_y_continuous(trans='log2') +
  #scale_fill_distiller(palette = "YlGnBu", direction=1) +
  labs(
       title = "BMP & SCM Type Cumulative Count",
       subtitle = "by BMP/SCM Ownership",
       x = "BMP/SCM install Date Estimate (Median Age of Surrounding Development)",
       y = "Cumulative Total of BMP/SCM in HUC12"
      )
```

```{r bmp_install_date_v_neighborhood_age, fig.width=12, fig.height= 9, fig.align='center'}
greensboro_bmp_year_area_gdf %>%
  filter(median_year >= 1950) %>%
  group_by(hu_12_name) %>% mutate(count=row_number(), cumarea=cumsum(area)) %>%
  ggplot(aes(x=median_year)) + 
  facet_wrap(hu_12_name~.) +
  #geom_line(aes(x=median_year,y=installdat, group=ownership, color=ownership)) + 
  geom_point(aes(x=median_year,y=installdat, group=ownership, color=ownership)) + 
  scale_fill_continuous(type = "viridis") +
  theme_bw() +
  #scale_y_continuous(trans='log2') +
  #scale_fill_distiller(palette = "YlGnBu", direction=1) +
  labs(
       title = "BMP & SCM Record Install Data VS Median Neighborhood Age",
       subtitle = "",
       x = "Median Age of Surrounding Development",
       y = "Install Date"
      )
```

```{r}
greensboro_bmp_year_area_gdf %>%
  filter(median_year >= 1960) %>%
  ggplot(aes(x=median_year, y=area) ) +
    geom_hex(bins = 70) +
    scale_fill_continuous(type = "viridis",trans='log2') +
    theme_bw()
```


## BMP Inlets

```{r}
query = paste('SELECT 
	inlet.assetid as inlet_assetid,
	bmp.objectid,
	bmp.installdat,
	bmp.bmptype,
	bmp.featuretyp,
	bmp.outletdiam,
	inlet.geom
FROM sw_inlets_greensboro as inlet, sw_waterbodies_bmp_scm_greensboro as bmp
WHERE ST_Intersects(inlet.geom, bmp.geom)')

bmp_inlets_gdf <- st_read(con,query = query)

query = paste('SELECT 
	bmp.*
FROM sw_inlets_greensboro as inlet, sw_waterbodies_bmp_scm_greensboro as bmp
WHERE ST_Intersects(inlet.geom, bmp.geom)')

bmps_gdf <- st_read(con,query = query)

```


```{r}
bmp_inlets_gdf %>%
ggplot() +
    geom_sf() +
    geom_sf(data=bmps_gdf, aes(fill=bmptype))
    #scale_fill_viridis_c(option = "plasma")
```

## Culverts

Calculate the total length of culverts
```{r}
huc12_culverts_df <- st_read(con, query=paste("SELECT sa.huc_12,sa.hu_12_name,sa.hu_10_name, 
	(
		sum(COALESCE(ST_Length(gc.geom),0) + 
			COALESCE(ST_Length(cc.geom),0) +
			COALESCE(ST_Length(rc.geom),0)
		   )
	) AS total_length_m,
	sa.geom
FROM huc12_study_area as sa
LEFT JOIN sw_culverts_greensboro as gc ON ST_CONTAINS(sa.geom, gc.geom)
LEFT JOIN sw_culverts_cary as cc ON ST_CONTAINS(sa.geom, cc.geom)
LEFT JOIN sw_culverts_raleigh as rc ON ST_CONTAINS(sa.geom, rc.geom)

GROUP BY sa.huc_12, sa.hu_12_name,sa.hu_10_name,  sa.geom"))

```

```{r}
#spplot(huc12_culverts_df,"total_length_m", main="Culvert Length (m)")

huc12_culverts_df %>%
ggplot() +
    #facet_grid(.~featuretyp) +
    geom_sf(aes(fill = total_length_m)) +
    scale_fill_viridis_c(option = "YlGnBu",trans='log2') +
    labs(color="Length (m)",
       title = "Culvert Length (m)") 
```

```{r}
#Import libraries
#library(spatstat)
#library(rgdal)

#huc12_culverts_df <- get_postgis_query(con, 
#geom_name = "geom")
#Convert roads spatial lines data frame to psp object
#psp_culvert_ms <- st_cast(huc12_culverts_df,"MULTILINESTRING")
#psp_culvert_ls <- st_cast(psp_culvert_ms,"LINESTRING")
#class(psp_culvert_ls)
#psp_culvert <- as.psp(huc12_culverts_df)
#Apply kernel density, however this is where I am unsure of the arguments
#culvert_density <- spatstat::density.psp(psp_culvert, sigma = 0.01, eps = 500) 

```

